services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U pipeline_user -d pipeline_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline:
    build: .
    restart: "no"
    profiles: [ "apps" ]  
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy # Wait until Postgres is fully ready to acce

volumes:
  pgdata: