# API CONFIG
api_url: "https://data.police.uk/api/crimes-street/all-crime"
months: 
  - "2026-01"
  #- "2026-02"
  #- "2026-03"
  #- "2026-04"
  #- "2026-05"

areas:
  #- "config/uk_crime_api/areas/_debug.yml"
  - "config/uk_crime_api/areas/london.yml"
  

initial_poly_split: 10

# Rate limiting and retries
max_retries: 5
wait_on_success: 2
wait_on_error: 5
timeout: 30


# Output 
output_dir_raw: "data/raw/uk_crime_api_call2"
output_dir_processed: "data/processed/uk_crime_processed"

#https://data.police.uk/api/crimes-street/all-crime?date=2024-01&poly=52.268,0.543:52.794,0.238:52.130,0.478
